#!/bin/bash
# All-in-one boot: self-generate secrets on first run (an Unraid Community
# Applications template cannot generate secrets, so the container must),
# stand up the embedded Postgres+TimescaleDB and Redis (unless the operator
# pointed at external ones), run migrations, then hand off to supervisord.
set -euo pipefail

log() { echo "[beacon-aio] $*"; }

mkdir -p /data
umask 077

# ─── Secrets: generated once into /data, reused on every boot ──────────────
if [ ! -f /data/secrets.env ]; then
  log "first boot: generating secrets into /data/secrets.env"
  cat > /data/secrets.env <<EOF
# Generated by the beacon-uptime all-in-one container on first boot.
# Back this file up together with pgdata/ — SESSION_SECRET signs active
# sessions and POSTGRES_PASSWORD is the embedded database's password.
SESSION_SECRET=$(openssl rand -hex 32)
POSTGRES_PASSWORD=$(openssl rand -hex 24)
EOF
fi
chmod 600 /data/secrets.env
# shellcheck disable=SC1091
set -a; source /data/secrets.env; set +a

umask 022

# ─── Database: embedded, unless DATABASE_URL was supplied ──────────────────
EMBEDDED_DB=false
if [ -z "${DATABASE_URL:-}" ]; then
  EMBEDDED_DB=true
  export DATABASE_URL="postgresql://beacon:${POSTGRES_PASSWORD}@127.0.0.1:5432/beacon"

  mkdir -p "$PGDATA"
  chown -R postgres:postgres /data/pgdata

  if [ ! -s "$PGDATA/PG_VERSION" ]; then
    log "initializing embedded PostgreSQL in $PGDATA"
    su postgres -c "$PG_BIN/initdb -D $PGDATA --auth=trust --username=postgres -E UTF8" >/tmp/initdb.log 2>&1 \
      || { cat /tmp/initdb.log; exit 1; }

    # TimescaleDB needs its background workers preloaded; Beacon's migrate
    # script (scripts/migrate.ts) creates the extension, a hypertable, two
    # continuous aggregates and retention/compression policies on top of it.
    cat >> "$PGDATA/postgresql.conf" <<CONF
listen_addresses = '127.0.0.1'
shared_preload_libraries = 'timescaledb'
timescaledb.max_background_workers = 8
max_worker_processes = 16
CONF

    log "starting PostgreSQL temporarily to create the beacon role/database"
    su postgres -c "$PG_BIN/pg_ctl -D $PGDATA -o '-c listen_addresses=127.0.0.1' -w start" >/tmp/pg-boot.log 2>&1 \
      || { cat /tmp/pg-boot.log; exit 1; }
    su postgres -c "$PG_BIN/psql -v ON_ERROR_STOP=1 -c \"ALTER USER postgres WITH PASSWORD '${POSTGRES_PASSWORD}';\""
    su postgres -c "$PG_BIN/psql -v ON_ERROR_STOP=1 -c \"CREATE ROLE beacon WITH LOGIN SUPERUSER PASSWORD '${POSTGRES_PASSWORD}';\""
    su postgres -c "$PG_BIN/psql -v ON_ERROR_STOP=1 -c \"CREATE DATABASE beacon OWNER beacon;\""
    su postgres -c "$PG_BIN/pg_ctl -D $PGDATA -m fast -w stop"
  else
    log "reusing existing PostgreSQL data dir in $PGDATA"
  fi

  # Long-running instance is supervisord's job from here on.
  cat > /etc/supervisor/conf.d/postgres.conf <<CONF
[program:postgres]
command=$PG_BIN/postgres -D $PGDATA
user=postgres
autorestart=true
priority=5
startsecs=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
CONF
else
  log "DATABASE_URL provided — skipping embedded PostgreSQL"
fi

# ─── Redis: embedded on loopback, unless REDIS_URL was supplied ────────────
if [ -z "${REDIS_URL:-}" ]; then
  export REDIS_URL="redis://127.0.0.1:6379"
  mkdir -p /data/redis
  chown -R redis:redis /data/redis

  cat > /etc/supervisor/conf.d/redis.conf <<CONF
[program:redis]
command=/usr/bin/redis-server --bind 127.0.0.1 --port 6379 --dir /data/redis --appendonly yes --daemonize no
user=redis
autorestart=true
priority=5
startsecs=2
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
CONF
else
  log "REDIS_URL provided — skipping embedded Redis"
fi

# ─── Wait for the database, then migrate ────────────────────────────────────
if [ "$EMBEDDED_DB" = true ]; then
  su postgres -c "$PG_BIN/pg_ctl -D $PGDATA -o '-c listen_addresses=127.0.0.1' -w start" >/tmp/pg-boot2.log 2>&1 \
    || { cat /tmp/pg-boot2.log; exit 1; }
else
  log "waiting for external database..."
  n=0
  until pg_isready -d "$DATABASE_URL" -q 2>/dev/null; do
    n=$((n + 1))
    [ "$n" -ge 20 ] && { log "ERROR: database unreachable after 20 attempts"; exit 1; }
    sleep 3
  done
fi

log "running database migrations (this also requires the timescaledb extension on the target database)"
node dist/scripts/migrate.js

if [ "$EMBEDDED_DB" = true ]; then
  # Hand the long-running instance over to supervisord instead of running
  # two postmasters against the same PGDATA.
  su postgres -c "$PG_BIN/pg_ctl -D $PGDATA -m fast -w stop"
fi

log "starting supervisord (app, worker, scheduler$([ "$EMBEDDED_DB" = true ] && echo ', postgres')$([ -f /etc/supervisor/conf.d/redis.conf ] && echo ', redis'))"
exec /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf
